# Generated by Django 2.2 on 2019-04-06 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('exams_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('very_bad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                                          django.core.validators.MaxValueValidator(
                                                                              100)])),
                ('bad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                                     django.core.validators.MaxValueValidator(100)])),
                ('moderate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                                          django.core.validators.MaxValueValidator(
                                                                              100)])),
                ('good', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                                      django.core.validators.MaxValueValidator(100)])),
                ('very_good', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0),
                                                                           django.core.validators.MaxValueValidator(
                                                                               100)])),
            ],
        ),
        migrations.AddField(
            model_name='examsheet',
            name='marks_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examsheets',
                                    to='exams_api.MarksRange'),
        ),
    ]
