# Generated by Django 2.2 on 2019-04-03 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksheet',
            old_name='user',
            new_name='creator',
        ),
        migrations.AlterUniqueTogether(
            name='tasksheet',
            unique_together={('creator', 'title', 'exam_sheet')},
        ),
    ]
