# Generated by Django 2.2 on 2019-04-03 19:51

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('exams_api', '0003_auto_20190403_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, validators=[rest_framework.compat.MinValueValidator(0)]),
        ),
    ]
